Refs # Handle more than 2 events
ideacrew/gluedb pull request #15
Opened 2021-03-13 19:39 UTC by saimekala07

Adding eligible criteria to group more than 2 events.
Adding additional action to handle retro events

2021-03-13 19:42 UTC, saimekala07 commented on app/models/enrollment_action/base.rb
> +      @additional_action = additional_init
any better name suggestions for `additional_action`?

2021-03-13 19:42 UTC, saimekala07 commented on app/models/enrollment_action/base.rb
> +        ::EnrollmentAction::RetroContinuityAndTerm,
any better name suggestions for enrollment actions

2021-03-25 00:10 UTC, TreyE requested changes
Requested changes, missing spec and I don't understand how we are proving we didn't change anything.

2021-03-25 00:10 UTC, TreyE commented on app/models/external_events/enrollment_event_notification.rb
>      def is_adjacent_to?(other)
Couple issues here.  One of the most important parts here is knowing that was have impacted how chunks are constructed only for this specific case - and left it alone for everyone else.

Given the above:
- I don't see how we construct chunks in a way that considers 3 events while only considering 2 at a time.  We might need to go up a level and find a way to consider an arbitrary set of chunks, possibly by doing more than one 'splitting' pass, or very early keeping any chunks which net out to exactly 2 chunks.
- I don't see how we can be sure that it affects this case and only this case without a spec, and without executing some examples that show you get what you expect for both the old and new behaviour.  Most likely the spec will need to involve 'jumping up a level' to app/business_processes/handlers/enrollment_event_enrich_handler.rb - or mimicing it's behaviour in order to make sure chunks are organized as we expect without impacting existing functionality.

2021-04-08 16:42 UTC, saimekala07 commented on app/models/external_events/enrollment_event_notification.rb
>      def is_adjacent_to?(other)
Currently we are handling/checking an event adjacent is another event and grouping them, if all the event happened in a given year only.

Added new logic will check for event adjacent is another event across the year for the specific retro case.
Scenario1:
-  group 3 events
Scenario1:
The current year(ex: 2021) canceled not terminated
Added retro coverage(ex: 2020)
Renewal created.

- group 2 events
Scenario2:(selected optional not to generate renewal )
The current year(ex: 2021) canceled not terminated
Added retro coverage(ex: 2020).

- plan change and dependent drop/add's that grouped happening for a given year shouldn't have any impacts by the new changes.

2021-04-15 00:44 UTC, TreyE requested changes
I've re-worked and simplified how we identify 3 enrollments at a time that qualify for the special treatment, and leave the rest of them alone.

I think we need to take a quick look at the specs you wrote to make sure that either they aren't testing the wrong thing, or, more likely, they found a bug in my implementation.

This approach should allow us to keep the existing behaviour more or less how it is, while grabbing only the very special cases where 3 enrollments need to be considered.

2021-04-21 17:06 UTC, TreyE approved these changes
Looks correct.

2021-04-22 16:30 UTC, merged