Merge pull request #55 from ideacrew/180365353-fix-missing-terms
ideacrew/gluedb pull request #187
Opened 2024-03-18 20:05 UTC by mdkaraman

Correct missing terminations and incorrect interpretation of events.

2024-03-22 12:17 UTC, raghuramg commented on app/models/external_events/enrollment_event_notification.rb
> +      ["urn:openhbx:terms:v1:enrollment#terminate_enrollment"]
if is_coverage_starter? returns `false`, we're explicitly returning the terminate_enrollment event. Is there any other event that could occur? instead can we say `[enrollment_action]` here.

2024-03-22 12:19 UTC, raghuramg requested changes
left comment

2024-03-22 13:39 UTC, mdkaraman commented on app/models/external_events/enrollment_event_notification.rb
> +      ["urn:openhbx:terms:v1:enrollment#terminate_enrollment"]
@raghuramg good question!  My understanding is that there are multiple kinds of events that begin coverage, but only one event that can terminate coverage.  All the events that can begin coverage are accounted for on line 87.

That leaves only the events that could terminate coverage, which I'm pretty sure is limited to `urn:openhbx:terms:v1:enrollment#terminate_enrollment`.  Note that cancels and terminations in Enroll are both sent to Glue using this event: https://github.com/ideacrew/enroll/blob/dd145cd89b5b5cb22ac2074d6d53de0070f8158c/app/models/queries/ivl_sep_events.rb#L20

 @TreyE please review and confirm my understanding when you have a chance.  If there are other kinds of events that I'm missing then I can see the need for a change.  However, I'd like to avoid new development here unless it's absolutely necessary.

2024-03-25 16:04 UTC, TreyE approved these changes

2024-03-26 00:44 UTC, TreyE commented on app/models/external_events/enrollment_event_notification.rb
> +      ["urn:openhbx:terms:v1:enrollment#terminate_enrollment"]
This is the correct understanding.

2024-03-27 17:02 UTC, raghuramg approved these changes
LGTM

2024-03-27 17:02 UTC, merged