Fixed Start Date Bug on Glue
ideacrew/gluedb pull request #201
Opened 2024-05-29 14:19 UTC by jayreddy519

https://www.pivotaltracker.com/n/projects/2640060/stories/187603029

Issue:

When we are sending files to EDI, we should pick the date based on member date on xml.

2024-05-30 13:20 UTC, jacobkagon approved these changes

2024-05-30 13:29 UTC, TreyE requested changes

2024-05-30 13:29 UTC, TreyE commented on app/models/enrollment_action/dependent_add.rb
>          end
The logic here is much more difficult.

1. First, if this individual isn't one of the people being added back (i.e. they aren't in the list of people already on the Policy *and* the list of people we're trying to 'add' (via the XML) - use the original date and original logic).
2. If we are trying to add them back and they are already on the Enrollment, there's a couple different things we need to do in choosing the start date:
    1. If the re-add of the individual would make the coverage continuous the we *do* want to use the original date from the policy
    2. If there would be a gap in coverage, we want to use the start date from the XML
    3. Neither of these things really have to do with the current status of the member on the policy, as policy termination dates can be in the future making the current 'state' of the record not matter as much as the start and end dates that might already be there vs the dates that come in on the XML the things we need to compare
    4. I think the easiest thing we can do here is look and see if they are already on the policy - if they are, and they don't have an end date on the policy, we just use the existing date from the policy - otherwise we need to branch off into the weird logic - and that's the part that will be complicated

2024-05-30 13:29 UTC, TreyE commented on spec/models/enrollment_action/dependent_add_spec.rb
> +
We're going to need, at minimum, a test case for the contiguous coverage case, and a test case for the 'gapped' coverage case.

2024-06-05 13:35 UTC, jacobkagon approved these changes
Updated logic looks good.

2024-06-12 16:14 UTC, TreyE approved these changes

2024-06-12 16:28 UTC, merged