adding effectuation carrier IDS to the chain of responsibilities and d…
ideacrew/gluedb pull request #25
Opened 2021-04-16 15:44 UTC by nks2109

…emographic changes

2021-04-20 22:52 UTC, TreyE requested changes
Please see my notes.

2021-04-20 22:52 UTC, TreyE commented on app/models/enrollment_action/action_publish_helper.rb
> +      end
I'm not sure this will work as implemented - if the node doesn't exist you will need to create it.

This begins I believe starting with anything below cv:id.

I also believe your xpath is not correct, I believe it should be: cv:id/cv:alias_ids/cv:alias_id/cv:id.

This method doesn't target a specific member, it would put the same member ID on all members - which is not correct.

I don't think I see a spec, did I miss it?

2021-04-20 22:52 UTC, TreyE commented on app/views/enrollment_events/_policy.xml.haml
> +                  %id= "urn:openhbx:hbx:me0:resources:v1:person:policy_id##{enrollee.cp_id}"
Don't think I see a spec for this change, did I miss it?

2021-04-20 22:52 UTC, TreyE commented on app/models/enrollment_action/action_publish_helper.rb
> +    end
Same issues as above method.

2021-04-20 22:52 UTC, TreyE commented on app/models/enrollment_action/assistance_change.rb
> +        action_helper.set_carrier_policy_id("urn:openhbx:hbx:me0:resources:v1:person:policy_id##{en.cp_id}") if en.cp_id.present?
Shouldn't these calls target a specific member?

2021-04-30 03:34 UTC, saimekala07 commented on app/models/enrollment_action/action_publish_helper.rb
> +      alias_id_nodes = node.xpath("cv:member/cv:id//cv:alias_ids/cv:alias_id/cv:id", XML_NS)
Looks like XPath is incorrect` //`

2021-04-30 03:46 UTC, saimekala07 commented on spec/models/enrollment_action/action_publish_helper_spec.rb
> +describe EnrollmentAction::ActionPublishHelper, "told to set affected and enrolles end dates, when member node exists" do
description update required.

2021-04-30 03:58 UTC, saimekala07 commented on app/models/enrollment_action/action_publish_helper.rb
> +      alias_id_nodes = node.xpath("cv:member/cv:id//cv:alias_ids/cv:alias_id/cv:id", XML_NS)
Add unit level spec for new methods.

2021-04-30 04:01 UTC, saimekala07 commented on app/models/enrollment_action/active_renewal.rb
> +          if en.c_id.present? || en.cp_id.present?
Is this change surrounded by some settings, as this is specific to Maine.

2021-04-30 04:13 UTC, saimekala07 commented on app/views/enrollment_events/_policy.xml.haml
> +          = render :partial => "enrollment_events/alias_id", :locals => { :enrollee => enrollee }
Do we support `alias_id` for member in current CV?

2021-04-30 13:22 UTC, nks2109 commented on app/views/enrollment_events/_policy.xml.haml
> +          = render :partial => "enrollment_events/alias_id", :locals => { :enrollee => enrollee }
Yes, we are supporting

2021-04-30 13:28 UTC, nks2109 commented on spec/models/enrollment_action/action_publish_helper_spec.rb
> +describe EnrollmentAction::ActionPublishHelper, "told to set affected and enrolles end dates, when member node exists" do
Sure

2021-04-30 13:28 UTC, nks2109 commented on app/models/enrollment_action/action_publish_helper.rb
> +      alias_id_nodes = node.xpath("cv:member/cv:id//cv:alias_ids/cv:alias_id/cv:id", XML_NS)
I will add them

2021-05-07 12:11 UTC, saimekala07 commented on app/models/enrollment_action/carrier_switch.rb
>            member_date_map[en.m_id] = en.coverage_start
Don't we need to send carrier_assigned_ids in termination file

2021-05-07 13:22 UTC, saimekala07 commented on app/models/enrollment_action/action_publish_helper.rb
> +    def add_carrier_assigned_ids(controller, enrollee, member_id_node)
Do we need this method if not please remove

2021-05-07 13:27 UTC, saimekala07 commented
Spec missing for enrollment actions, please add spec for anyone of the enrollment action with spec that sets carrier assigned ids.

2021-05-12 12:25 UTC, saimekala07 commented on app/models/enrollment_action/cobra_new_policy_switchover.rb
>        term_helper.set_member_starts(member_date_map)
https://github.com/ideacrew/gluedb/pull/25/files#diff-06f648a4b1ba6a4100756b9cfdc09bf3fe00d636263e68f6aad9f5525380630eR55

2021-05-12 12:42 UTC, saimekala07 commented on spec/models/enrollment_action/active_renewal_spec.rb
> +  let!(:enrollee_primary) { double(:m_id => 1, :coverage_start => :one_month_ago, :c_id => nil, :cp_id => nil) }
Can we have one spec for enrollment action that has enrollees with c_id and cp_id..and action helper sets carrier assigned to it.

2021-05-12 16:03 UTC, TreyE commented on app/models/enrollment_action/cobra_new_policy_switchover.rb
>        term_helper.set_member_starts(member_date_map)
In this particular case, we are building an entire new policy, so no, the carrier assigned IDs should not be present.

They DO need to be present on the termination when it is sent.

2021-05-12 16:04 UTC, TreyE commented on app/models/enrollment_action/action_publish_helper.rb
> +    def add_carrier_assigned_ids(controller, enrollee, member_id_node)
Will remove, update forthcomming.

2021-05-12 16:05 UTC, TreyE commented on spec/models/enrollment_action/active_renewal_spec.rb
> +  let!(:enrollee_primary) { double(:m_id => 1, :coverage_start => :one_month_ago, :c_id => nil, :cp_id => nil) }
Gotcha - you want a spec where we've got a case with a nice mix between the two.  Gimme some time I will do it.

2021-05-12 16:38 UTC, saimekala07 commented
Looks good Approved.

2021-05-12 16:40 UTC, saimekala07 approved these changes
Added changes to include carrier assigned ids.

2021-05-17 20:38 UTC, merged