Me county fips code
ideacrew/gluedb pull request #29
Opened 2021-05-03 22:13 UTC by saipraveen18

2021-05-12 23:38 UTC, TreyE requested changes
Please see my notes.

2021-05-12 23:38 UTC, TreyE commented on app/models/address.rb
> +    attrs_to_match = [:address_type, :address_1, :address_2, :city, :state, :zip, :location_county_code]
Shouldn't this also include county name in the comparison?

2021-05-12 23:38 UTC, TreyE commented on app/models/remote_resources/address.rb
> +    element :location_county_code, String, tag: "location_county_code"
Shouldn't we also check for county name here as well if we have it?

2021-05-12 23:38 UTC, TreyE commented on app/models/parsers/edi/etf/responsible_party_parser.rb
> +            county_code = @loop["L2100A"]["N4"][4].blank? ? nil : @loop["L2100A"]["N4"][4]
Number of issues here:
1. FIPS codes aren't present in the N4 for responsible parties.
2. You won't find responsible party info in the 2100A loop.  It lives in G or H or something like that.

2021-05-12 23:38 UTC, TreyE commented on app/models/parsers/edi/etf/person_loop.rb
> +        end
County code, if it exists, lives in the N406 loop (index `6` in the N4 array) and this is if and only if the N405 (element `5` in the array) is present with a value of 'CY'.

2021-05-12 23:38 UTC, TreyE commented on spec/models/parsers/edi/etf/person_parser_spec.rb
> +        'N4' => ['', city, state, zip, county_code]
Same deal with N4 structure as mentioned above.  N404 is actually the **country** code - which we never provide.

2021-05-13 15:49 UTC, saipraveen18 commented on app/models/address.rb
> +    attrs_to_match = [:address_type, :address_1, :address_2, :city, :state, :zip, :location_county_code]
Currently, we are not sending County name from upstream (EA)

2021-05-13 15:51 UTC, saipraveen18 commented on app/models/remote_resources/address.rb
> +    element :location_county_code, String, tag: "location_county_code"
Currently, we are not sending County name from upstream (EA)

2021-05-13 15:53 UTC, saipraveen18 commented on app/models/parsers/edi/etf/person_loop.rb
> +        end
Fixed

2021-05-14 18:52 UTC, TreyE commented on app/models/address.rb
> +    attrs_to_match = [:address_type, :address_1, :address_2, :city, :state, :zip, :location_county_code]
Correct

2021-05-14 18:55 UTC, TreyE approved these changes
Looks correct.

2021-05-26 14:04 UTC, merged