Enrollment batch enhancement
ideacrew/gluedb pull request #5
Opened 2021-03-02 15:33 UTC by saimekala07

2021-03-18 23:12 UTC, TreyE requested changes
Please see my comments.

2021-03-18 23:12 UTC, TreyE commented on app/models/enrollment_events/transaction.rb
> +    index({batch_id: 1, payload: 1, headers: 1,  event_time: 1})
Don't index the payload - it's a big and you are already extracting the data at the Batch level.  It will most likely result in a huge index which doesn't actually hep you find anything faster.  Keep the other key indexes though.

2021-03-18 23:12 UTC, TreyE commented on app/models/listeners/enrollment_event_batch_handler.rb
> +          resource_error_broadcast("unknown_error", "500", body, m_headers)
Either we want to find some way to leave the message on the queue (i.e. don't take it off the queue and just crash), or we should find a way to serialize and find out what the error was - I think if you dig around in other listeners there's a way we write out the exception to json or something.

2021-03-18 23:12 UTC, TreyE commented on app/models/listeners/enrollment_event_batch_handler.rb
> +             batch.process!
May I suggest we invert the order of events?  Can we not move the status until we know for sure we have put the message onto AMQP?

2021-03-18 23:12 UTC, TreyE commented on script/amqp/configure_amqp_topology.rb
> +Listeners::EnrollmentEventBatchHandler.run
I would not add this to this script - this script is intended to set up some AMQP plumbing, not to actually run a listener.  I would actually remove this script entirely.

2021-03-18 23:12 UTC, TreyE commented on script/amqp/enrollment_batch_processor_listener.rb
> +Listeners::EnrollmentEventBatchProcessor.run
I don't think we need to actually create a separate script for this, add your list of listener classes to script/amqp/employer_workers.rb, and I think as long as they support the ".run" method they'll get kicked off.

And yes, I know the file is strangely named, but it's already configured to get booted in our environments automatically.

2021-03-19 14:24 UTC, saimekala07 commented on app/models/enrollment_events/transaction.rb
> +    index({batch_id: 1, payload: 1, headers: 1,  event_time: 1})
Removed payload from index.

2021-03-19 15:38 UTC, saimekala07 commented on app/models/enrollment_events/batch.rb
> +      }).any?
was expecting it will be done by default scope, but adding state check too just to make sure we are checking on open batch,

2021-03-19 17:30 UTC, saimekala07 commented on app/models/listeners/enrollment_event_batch_handler.rb
> +             batch.process!
@TreyE conformed no changes required.

2021-03-19 17:30 UTC, saimekala07 commented on app/models/enrollment_events/batch.rb
> +    default_scope ->{ where(aasm_state: 'open') }
@TreyE do you want me to remove default scope.

2021-03-19 17:44 UTC, saimekala07 commented on script/amqp/enrollment_batch_processor_listener.rb
> +Listeners::EnrollmentEventBatchProcessor.run
removed

2021-03-19 17:44 UTC, saimekala07 commented on script/amqp/configure_amqp_topology.rb
> +Listeners::EnrollmentEventBatchHandler.run
reverted

2021-03-23 18:36 UTC, TreyE requested changes
Last change and then we are good to test.

2021-03-23 18:36 UTC, TreyE commented on app/models/enrollment_events/batch.rb
> +    default_scope ->{ where(aasm_state: 'open') }
Please remove default scope and apply needed scopes to queries below and in your models.

2021-03-24 12:36 UTC, TreyE approved these changes
Looks good.

2021-04-20 16:19 UTC, TreyE approved these changes
Looks correct.

2021-04-22 16:29 UTC, merged