Endpoint for search of enrolled subjects.
ideacrew/gluedb pull request #53
Opened 2021-11-09 17:25 UTC by TreyE

Creates endpoints to both express a list of subscribers enrolled under a particular HIOS ID and year, as well as coverage history for those subscribers.

2021-12-08 17:37 UTC, nks2109 commented on app/models/generators/coverage_information_serializer.rb
> +          total_responsible_amt: policy.total_responsible_amount.to_f,
please check this attribute name total_responsible_amount

2021-12-08 17:56 UTC, nks2109 commented on app/models/generators/coverage_information_serializer.rb
> +      date.strftime("%Y-%m-%d")
irb(main):090:0* Policy.first.subscriber.coverage_start.to_s
=> "01-01-2022"
I verified the date format on a test environment for coverage_start i.e ("%m-%d-%Y). Can you once again confirm the format how we are expecting?

2021-12-08 18:02 UTC, nks2109 commented on app/models/generators/coverage_information_serializer.rb
> +          issuer_assigned_policy_id: enrollee.cp_id,
Just a suggestion can you use both carrier_member_id & carrier_policy_id instead c_id & cp_id respectively

2021-12-08 18:19 UTC, nks2109 commented on app/models/generators/coverage_information_serializer.rb
> +      @policy.aptc_credits.each do |credit|
Please add a condition to check whether aptc_credits are present for the @policy like
if @policy.aptc_credits.count > 0

2021-12-08 18:36 UTC, nks2109 commented on app/models/generators/coverage_information_serializer.rb
> +          service_area: "",
can you add a comment for service_area field that how we are going to pull later this value. It will be helpful for other devs.

2021-12-08 19:29 UTC, nks2109 requested changes
Could you add a test case for subscriber segment?

2021-12-09 03:02 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +          total_responsible_amt: policy.total_responsible_amount.to_f,
Modified

2021-12-09 03:03 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +          service_area: "",
Not sure how are we gonna pull this value, but added a comment and for now sending empty value

2021-12-09 03:03 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +          issuer_assigned_policy_id: enrollee.cp_id,
Modified

2021-12-09 03:04 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +      @policy.aptc_credits.each do |credit|
There is no need to add a check, if aptc_credits are present then it will go inside the loop otherwise it doesn't

2021-12-09 03:04 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +      date.strftime("%Y-%m-%d")
The format I am expecting in my report is (year, month and day).

2021-12-09 14:38 UTC, nks2109 approved these changes

2021-12-09 14:48 UTC, merged