Ticket 181218888
ideacrew/gluedb pull request #82
Opened 2022-02-22 19:04 UTC by saipraveen18

2022-02-25 19:10 UTC, nks2109 requested changes

2022-02-25 19:10 UTC, nks2109 commented on app/models/generators/coverage_information_serializer.rb
> +                                       as_dollars((total_premium_amount - aptc_amount)).to_f
you can do this as_dollars(total_premium_amount - aptc_amount)

2022-02-25 22:07 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +                                                                  :m_id => person.authority_member_id}},
Not sure  - why can't we take authority member id on person? Does enrollee m_id and person's authority_member_id not the same??

2022-02-25 22:07 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +                                       as_dollars((total_premium_amount - aptc_amount)).to_f
I am using as_dollars and also to_f, will this cause any issues?

2022-02-25 22:14 UTC, nks2109 commented on app/models/generators/coverage_information_serializer.rb
> +                                                                  :m_id => person.authority_member_id}},
In some cases, we might just put the value of authority_member_id on a person object but the actual m_id is the authority_member's hbx_member_id.

2022-02-26 15:12 UTC, nks2109 approved these changes
Premium values are not considering from plan table which looks good.

2022-02-28 14:33 UTC, nks2109 approved these changes

2022-03-09 14:55 UTC, saipraveen18 commented on app/models/generators/coverage_information_serializer.rb
> +                                                                  :m_id => person.authority_member_id}},
Updated. Fetching m_id from person's authority member hbx_member_id

2022-03-09 15:09 UTC, merged